/**
 * MIT License - 2021
 */
package claudiosoft.pocbase;

/**
 * A convenient Java exception to identify errors generated by JarBox
 */
public class POCException extends Exception {

    public POCException(String errorMessage) {
        super(errorMessage);
    }

    public POCException(String errorMessage, Throwable ex) {
        super(errorMessage, ex);
    }
}
